name: Publish
on:
  workflow_dispatch:
    branches:
      - main

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Publish module to PowerShell Gallery
          env:
            API_KEY: ${{ secrets.API_KEY }}
          run: .\publish.ps1
          shell: powershell
