name: Publish
on: workflow_dispatch
jobs:
    build:
      name: Publish
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - name: Publish module to PowerShell Gallery
          env:
            API_KEY: ${{ secrets.API_KEY }}
          run: .\publish.ps1
          shell: pwsh
